{{- if (index (index .Values "csi-rclone") "enabled") }}
apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData: 
  {{- range $key, $value := index (index .Values "csi-rclone") "params" }}
  {{ $key }}: {{ quote $value }}
  {{- end }}
  {{- if (index (index .Values "csi-rclone") "useGkeAuth") }}
  gcs-service-account-credentials: '{{ .Values.gke.keyJSON }}'
  {{- end }}
{{- end }}