---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    # To enable hints based autodiscover uncomment this:
    # metricbeat.autodiscover:
    #  providers:
    #    - type: kubernetes
    #      host: ${NODE_NAME}
    #      hints.enabled: true

    processors:
      - add_cloud_metadata:

    cloud.id: {{ .Values.filebeat.elasticCloudId | quote }}
    cloud.auth: {{ .Values.filebeat.elasticsearchCloudAuth | quote }}

    output.elasticsearch:
      hosts: ['{{ .Values.filebeat.elasticsearchHost }}:{{ .Values.filebeat.elasticsearchPort }}']
      username: {{ .Values.filebeat.elasticsearchUsername | quote }}
      password: {{ .Values.filebeat.elasticsearchPassword | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-modules
  labels:
    k8s-app: metricbeat
data:
  system.yml: |-
    - module: system
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        #- core
        #- diskio
        #- socket
      processes: ['.*']
      process.include_top_n:
        by_cpu: 5      # include top 5 processes by CPU
        by_memory: 5   # include top 5 processes by memory

    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      period: 10s
      host: ${NODE_NAME}
      hosts: ["localhost:10255"]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-config
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: false

    processors:
      - add_cloud_metadata:

    cloud.id: {{ .Values.filebeat.elasticCloudId | quote }}
    cloud.auth: {{ .Values.filebeat.elasticsearchCloudAuth | quote }}

    output.elasticsearch:
      hosts: ['{{ .Values.filebeat.elasticsearchHost }}:{{ .Values.filebeat.elasticsearchPort }}']
      username: {{ .Values.filebeat.elasticsearchUsername | quote }}
      password: {{ .Values.filebeat.elasticsearchPassword | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-deployment-modules
  labels:
    k8s-app: metricbeat
data:
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
        - event
      period: 10s
      host: ${NODE_NAME}
      hosts: ["{{ .Release.Name }}-kube-state-metrics:8080"]
