{{- if .Values.metricbeat.enabled }}
# Deploy a Metricbeat instance per node for node metrics retrieval
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
spec:
  template:
    metadata:
      labels:
        k8s-app: metricbeat
    spec:
      serviceAccountName: metricbeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:{{ required "A valid .Values.metricbeat.version entry required!" .Values.metricbeat.version }}
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
          "-system.hostfs=/hostfs",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: {{ required "A valid .Values.metricbeat.elasticsearchHost entry required!" .Values.metricbeat.elasticsearchHost | quote }}
        - name: ELASTICSEARCH_PORT
          value: {{ required "A valid .Values.metricbeat.elasticsearchPort entry required!" .Values.metricbeat.elasticsearchPort | quote }}
        - name: ELASTICSEARCH_USERNAME
          value: {{ required "A valid .Values.metricbeat.elasticsearchUsername entry required!" .Values.metricbeat.elasticsearchUsername | quote }}
        - name: ELASTICSEARCH_PASSWORD
          value: {{ required "A valid .Values.metricbeat.elasticsearchPassword entry required!" .Values.metricbeat.elasticsearchPassword | quote }}
        - name: ELASTIC_CLOUD_ID
          value: {{ required "A valid .Values.metricbeat.elasticCloudId entry required!" .Values.metricbeat.elasticCloudId | quote }}
        - name: ELASTIC_CLOUD_AUTH
          value: {{ required "A valid .Values.metricbeat.elasticsearchCloudAuth entry required!" .Values.metricbeat.elasticsearchCloudAuth | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: proc
          mountPath: /hostfs/proc
          readOnly: true
        - name: cgroup
          mountPath: /hostfs/sys/fs/cgroup
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: config
        configMap:
          defaultMode: 0600
          name: metricbeat-daemonset-config
      - name: modules
        configMap:
          defaultMode: 0600
          name: metricbeat-daemonset-modules
      - name: data
        hostPath:
          path: /var/lib/metricbeat-data
          type: DirectoryOrCreate

---
# Deploy singleton instance in the whole cluster for some unique data sources, like kube-state-metrics
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
spec:
  template:
    metadata:
      labels:
        k8s-app: metricbeat
    spec:
      serviceAccountName: metricbeat
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:{{ required "A valid .Values.metricbeat.version entry required!" .Values.metricbeat.version }}
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: {{ required "A valid .Values.metricbeat.elasticsearchHost entry required!" .Values.metricbeat.elasticsearchHost | quote }}
        - name: ELASTICSEARCH_PORT
          value: {{ required "A valid .Values.metricbeat.elasticsearchPort entry required!" .Values.metricbeat.elasticsearchPort | quote }}
        - name: ELASTICSEARCH_USERNAME
          value: {{ required "A valid .Values.metricbeat.elasticsearchUsername entry required!" .Values.metricbeat.elasticsearchUsername | quote }}
        - name: ELASTICSEARCH_PASSWORD
          value: {{ required "A valid .Values.metricbeat.elasticsearchPassword entry required!" .Values.metricbeat.elasticsearchPassword | quote }}
        - name: ELASTIC_CLOUD_ID
          value: {{ required "A valid .Values.metricbeat.elasticCloudId entry required!" .Values.metricbeat.elasticCloudId | quote }}
        - name: ELASTIC_CLOUD_AUTH
          value: {{ required "A valid .Values.metricbeat.elasticsearchCloudAuth entry required!" .Values.metricbeat.elasticsearchCloudAuth | quote }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: metricbeat-deployment-config
      - name: modules
        configMap:
          defaultMode: 0600
          name: metricbeat-deployment-modules
{{- end }}
