apiVersion: v2
appVersion: "1.0"
description: Setup a silta kubernetes cluster.
name: silta-cluster
version: 0.2.3
dependencies:
- name: traefik
  version: 1.86.x
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 10.4.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: deploymentRemover.enabled
- name: kube-state-metrics
  version: 2.2.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: kube-state-metrics.enabled
- name: minio
  version: 2.5.14
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: minio.enabled
- name: csi-rclone
  version: 0.1.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: csi-rclone.enabled
- name: cert-manager
  version: 0.10.x
  repository: https://charts.jetstack.io/
  condition: cert-manager.enabled
- name: silta-downscaler
  version: 0.1.0
  repository: file://../silta-downscaler
  condition: silta-downscaler.enabled