dependencies:
- name: ambassador
  version: 2.12.x
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 8.1.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: deploymentRemover.enabled
- name: kube-state-metrics
  version: 2.2.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: kube-state-metrics.enabled
- name: newrelic-infrastructure
  version: 0.13.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: newrelic-infrastructure.enabled
- name: minio
  version: 2.5.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: minio.enabled
- name: csi-rclone
  version: 0.1.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: csi-rclone.enabled
