dependencies:
- name: nfs-server-provisioner
  version: 0.1.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: nfs-server-provisioner.enabled
- name: ambassador
  version: 2.9.x
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 4.3.x
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: kube-state-metrics
  version: 0.14.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: metrics.enabled
- name: minio
  version: 2.4.x
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: minio.enabled
- name: csi-rclone
  version: 0.1.x
  repository: https://storage.googleapis.com/charts.wdr.io
  condition: csi-rclone.enabled
