# Main domain of the cluster.
clusterDomain: "silta.wdr.io"

ambassador:
  service:
    https:
      enabled: false
    annotations:
      getambassador.io/config: |
        ---
        apiVersion: ambassador/v1
        kind: Module
        name: ambassador
        config:
          service_port: 8080
          use_remote_address: true
  adminService:
    create: true

nfs-server-provisioner:
  enabled: true
  persistence:
    enabled: true
    storageClass: standard
    size: 10Gi
  storageClass:
    defaultClass: false
    name: silta-shared
    parameters:
      mountOptions:
        - vers=4.1
  resources:
    limits:
      cpu: 200m
      memory: 1G
    requests:
      cpu: 200m
      memory: 1G

# https://github.com/wunderio/charts/blob/master/csi-rclone/values.yaml
csi-rclone:
  enabled: false
  # Use silta cluster gke credentials. This is used when remote type is set to "google cloud storage".
  useGkeAuth: false
  # Do not allow csi-rclone subchart to install default secret because we want to generate it ourselves.
  defaultParams: false
  storageClass:
    name: "silta-shared"
  params:
    remote: "s3"
    remotePath: "projectname"
    
    # Minio as S3 provider
    s3-provider: "Minio"
    s3-endpoint: "http://minio-release.default:9000"
    # Default credentials of minio chart https://github.com/helm/charts/tree/master/stable/minio
    s3-access-key-id: "AKIAIOSFODNN7EXAMPLE"
    s3-secret-access-key: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

minio:
  enabled: false

# SSH Jumphost settings
gitAuth:
  host: 'github.com'
  organisation: ''
  apiToken: ''

# Deployment remover
deploymentRemover:
  # Github webhooks secret
  webhooksSecret: ''

# GKE Cluster settings
gke:
  keyJSON: ''
  projectName: '' 
  computeZone: ''
  clusterName: ''

# Redis DB for remover queue
# https://github.com/helm/charts/tree/master/stable/redis
redis:
  password: ''
  cluster:
    enabled: 0
    slaveCount: 0

# Filebeat settings
filebeat:
  enabled: false
  version: ''
  elasticCloudId: ''
  elasticsearchHost: ''
  elasticsearchPort: ''
  elasticsearchUsername: ''
  elasticsearchPassword: ''
  elasticsearchCloudAuth: ''

# Metricbeat settings
metricbeat:
  enabled: false
  version: ''
  elasticCloudId: ''
  elasticsearchHost: ''
  elasticsearchPort: ''
  elasticsearchUsername: ''
  elasticsearchPassword: ''
  elasticsearchCloudAuth: ''
