apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-downscale-cron
spec:
  schedule: "{{ .Values.schedule }}"
  startingDeadlineSeconds: 3600
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ .Release.Name }}-downscaler
          containers:
          - name: downscaler-cron
            image: {{ .Values.image | quote }}
            command: ["/bin/sh", "-c"]
            args:
              - node downscale
            resources:
              {{ .Values.resources | toYaml | nindent 14 }}
            env:
              - name: PLACEHOLDER_SERVICE_NAME
                value: {{ .Release.Name }}-placeholder-upscaler
              - name: PLACEHOLDER_SERVICE_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
