{{- range $index, $mount := .Values.mounts }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Release.Name }}-{{ $mount.name }}
  labels:
    name: {{ $.Release.Name }}-{{ $mount.name }}
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ $mount.storage }}
  storageClassName: {{ $mount.storageClassName }}
  {{- if $mount.csiDriverName }}
  csi:
    driver: {{ $mount.csiDriverName }}
    volumeHandle: {{ $.Release.Name }}-{{ $mount.name }}
    volumeAttributes:
      remotePathSuffix: /{{ $.Release.Namespace }}/{{ $.Values.environmentName }}/{{ $mount.name }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ $mount.name }}
  labels:
    {{- include "drupal.release_labels" $ | nindent 4 }}
spec:
  storageClassName: {{ $mount.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ $mount.storage }}
  selector:
    matchLabels:
      name: {{ $.Release.Name }}-{{ $mount.name }}
---
{{- end }}

{{- if .Values.referenceData.enabled }}
{{- if eq .Values.referenceData.referenceEnvironment .Values.environmentName }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-reference-data
  labels:
    name: {{ .Release.Name }}-reference-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.referenceData.storage }}
  storageClassName: {{ .Values.referenceData.storageClassName }}
  {{- if .Values.referenceData.csiDriverName }}
  csi:
    driver: {{ .Values.referenceData.csiDriverName }}
    volumeHandle: {{ .Release.Name }}-reference-data
    volumeAttributes:
      remotePathSuffix: /{{ .Release.Namespace }}/{{ .Values.environmentName }}/reference-data
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "drupal.referenceEnvironment" . }}-reference-data
  labels:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.referenceData.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.referenceData.storage }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-reference-data
{{- end }}
{{- end }}
---
{{- if .Values.shell.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shell-keys
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
{{- end }}
