apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-php-conf
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
data:
  settings_silta: |
    <?php

    // Database settings.
    $databases['default']['default'] = [
      'database' => {{ .Values.mariadb.name }},
      'username' => getenv('DB_USER'),
      'password' => getenv('DB_PASS'),
      'host' => getenv('DB_HOST'),
      'port' => '3306',
      'driver' => 'mysql',
      'prefix' => '',
      'collation' => 'utf8mb4_general_ci',
    ];

    // Salt for one-time login links, cancel links, form tokens, etc.
    $settings['hash_salt'] = getenv('HASH_SALT');

    /**
     * If a volume has been set for private files, tell Drupal about it.
     */
    if (getenv('PRIVATE_FILES_PATH')) {
      $settings['file_private_path'] = getenv('PRIVATE_FILES_PATH');
    }

    /**
     * If Elasticsearch is enabled, add configuration for the Elasticsearch Helper module.
     */
    if (getenv('ELASTICSEARCH_HOST')) {
      $config['elasticsearch_helper.settings']['elasticsearch_helper']['host'] = getenv('ELASTICSEARCH_HOST');;
      $config['elasticsearch_helper.settings']['elasticsearch_helper']['port'] = "9200";
    }

    /**
     * Set the memcache server hostname when a memcached server is available
     */
    if (getenv('MEMCACHED_HOST')) {
      $settings['memcache']['servers'] = [getenv('MEMCACHED_HOST') . ':11211' => 'default'];
    }

    /**
     * Generated twig files should not be on shared storage.
     */
    $settings['php_storage']['twig']['directory'] = '../generated-php';

    /**
     * Make sure the dynamic environments are not blocked out as untrusted.
     */
    $settings['trusted_host_patterns'][] = '^.*\$';
